### ISSUE TITLE
Decreasing Line spacing closes tab

### ISSUE THREAD

**Issue by ciesiolka** [ChurchApps/FreeShow#495] opened 2024-05-08 14:47 UTC
First of all, I just discovered the project and it looks fantastic. Good job!
However, I'm finding a lot of small bugs. Here's one of them.

1. Insert a textbox
2. Open `Text` tab
![image](https://github.com/ChurchApps/FreeShow/assets/129899434/0f6a4f1b-f433-495b-b748-7cd03eb3f90e)
3. Letter spacing is set to `1`. Click `-` button next to the input box to reduce the value to 0.

Expected result:
1. The letters spacing is set to `0`.

Actual result:
1. The `Text` tab is closed.

Additional info:
* Modifying any other option in the Text tab first prevents this bug.

**Comment by vassbo** [comment] 2024-05-09 09:01
Thanks. This is not a bug, but I know there might be a better way to do this.

Clicking the "Text" button, will not just open the values, but apply some styling, in this case the change is minimal. That's why when setting the "Letter spacing" back to 0, means that all of the values are set back to default, and the inputs are closed again.

**Comment by ciesiolka** [comment] 2024-05-09 10:37
Thanks for reply. I got your point, yet I still consider it a bug as I can't apply negative letter spacing without first altering other parameter.

**Comment by vassbo** [comment] 2024-05-10 09:47
Right, I will see if I can stop it from closing when editing is active.

**Closed** 2024-05-10 14:48 UTC
Labels: question
