### ISSUE TITLE
Scripture feature crashes the software. 

### ISSUE THREAD

**Issue by BW6808** [ChurchApps/FreeShow#660] opened 2024-07-12 15:27 UTC
When I click on the scripture area, the whole program freezes until I close and re-open

**Comment by thirdybobiles** [comment] 2024-07-13 14:13
#630

**Comment by jzongker** [comment] 2024-07-15 04:18
Closing as a duplicate of #630 It'll be fixed in the next release.

**Closed by jzongker** 2024-07-15 04:18 UTC
