### ISSUE TITLE
Wireless Live Camera Feed Lag

### ISSUE THREAD

**Issue by Neoslyke** [ChurchApps/FreeShow#671] opened 2024-07-18 22:55 UTC
I'm using Iriun webcam which used phone as a wireless camera running on the same network, it lags so bad. It runs pretty smooth on VideoPsalm at maybe 30FPS of smoothness, but on FreeShow it's just unbareable. Any settings I should change?

**Comment by vassbo** [comment] 2024-07-19 06:29
I'm not sure why it lags, I just tested it and it seems to run smoothly. Do you get the same results with USB transferring, or with another app like Droidcam? Also, do you get the same lag when just previewing the feed in the "Media" tab, and not clicing it to output?

**Comment by Neoslyke** [comment] 2024-07-21 14:25
> I'm not sure why it lags, I just tested it and it seems to run smoothly. Do you get the same results with USB transferring, or with another app like Droidcam? Also, do you get the same lag when just previewing the feed in the "Media" tab, and not clicing it to output?

I didn't bother to try with USB transferring or DroidCam because I had no issue using the same setup on VideoPsalm, maybe I'm missing a driver that FreeShow depends on like K-Lite Codec Pack?

**Comment by vassbo** [comment] 2024-07-22 05:40
No worries. I'm just trying to see if the problem is within FreeShow itself or an incompatibility issue between Chromium and Iriun.
Can you please use a testing page like this: https://webcamtests.com/fps - And let me know if you experience the same amount of lag here?

**Closed** 2024-07-30 07:17 UTC
Labels: electron
