### ISSUE TITLE
Importing OpenLyrics without result

### ISSUE THREAD

**Issue by gyuris** [ChurchApps/FreeShow#422] opened 2024-02-29 10:59 UTC
I try to import OpenLyrics XMLs (in bundles), but FreeShow (1.1.4) does nothing. I got only a "in progress..." popup but no success.

The files, which I try to import is: https://github.com/gyuris/aszaf/releases/download/v1.0.4/Aszaf.csomag.7z

I see that the importer [is waiting XML source files](https://github.com/ChurchApps/FreeShow/blob/main/src/frontend/converters/opensong.ts#L41). No idea what to do.

**Comment by vassbo** [comment] 2024-02-29 11:15
The issue is due to the "<?xml version="1.0" encoding="UTF-8"?>" at the start of each file.
This will be fixed. But if you remove that line it will work.

**Comment by gyuris** [comment] 2024-02-29 14:37
Thanks for the clarification! The import is successfully after removing processing instructions. Please refer to this bug in OpenLP. There can be stylesheet instructions too: Example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="stylesheets.css" type="text/css"?>
```

**Comment by gyuris** [comment] 2024-03-11 23:48
A small comment to 7620c461a4911221f21714af62f8e4c724d2a802. This would be a more general solution.

```js
while (xml.indexOf("<?xml") >= 0) {
  xml = xml.split("\n").slice(1, xml.split("\n").length).join("\n")
}
```

**Comment by gyuris** [comment] 2024-03-12 09:16
Thanks for fixing this issue. I will promote the next release when this fix is released.  :-).

**Closed** 2024-03-28 08:50 UTC
Labels: bug
