### ISSUE TITLE
[Feature Request] Automatic CCLI reporting

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#879] opened 2024-10-10 16:29 UTC
Hi, is there a plan to implement Automatic CCLI reporting, or at least keeping track of CCLI usage for anual reporting?

Although I understand that this would probably require a more specific approach to song slides, perhaps making them a different category, with CCLI atributes.

**Comment by thebiblelover7** [comment] 2024-10-10 16:49
This is a duplicate of #572 and #776

**Comment by yurividal** [comment] 2024-10-10 17:00
Thanks and sorry for the duplicate post.
If there is no automatic way to report, perhaps Freeshow can save data to a CSV, which the church can submit once a year? (I believe that's how we are doing at the moment, with OpenSong).

**Closed** 2024-10-11 05:54 UTC
Labels: duplicate

**Comment by vassbo** [comment] 2024-10-11 05:58
@yurividal Maybe we can do that, are you willing to send an example of one of your CSV files to dev@freeshow.app so I can see the formatting used?!

**Comment by yurividal** [comment] 2024-10-11 08:44
@vassbo my bad. I was under the impression we had this on a CSV, its actually an XML. I spoke to the member of our team who is responsable for the reporting, and he said that the way it works is:

OpenSong generates a usage report XML, in the following format:

````
<?xml version="1.0" encoding="UTF-8"?>
<log>
  <Entry553>
  <Date>2021-11-13</Date>
  <Time>21:18:49</Time>
  <Description>3</Description>
  <FileName>Mission Praise/Lord for the years Your love has kept and guided</FileName>
  <title>Lord for the years</title>
  <author>Timothy Dudley Smith</author>
  <ccli>3274952</ccli>
  <HasChords>false</HasChords></Entry553>
  <Entry554>
  <Date>2021-11-14</Date>
  <Time>10:18:15</Time>
  <Description>5</Description>
  <FileName>Christian Hymns/Crown Him with many crowns</FileName>
  <title>Crown Him with many crowns</title>
  <author>Matthew Bridges, 1800-94 and Godfrey Thring, 1823-1903</author>
  <ccli>23938</ccli>
  <HasChords>false</HasChords></Entry554>
  <Entry555>
````
We then, use a custom script that reads this and manually inputs each song, by CCLI ID into the website. Its an automated process, but still, not as simple as uploading a CSV to CCLI.

Maybe if we can have Freeshow somehow keep record of the songs used, we can colab on a side-project script that will submit the data. Shouldn't be that hard, using python and selenium.

**Comment by vassbo** [comment] 2024-10-11 08:51
All right, I'm thinking JSON format.
I opened a new issue for it: https://github.com/ChurchApps/FreeShow/issues/883
