### ISSUE TITLE
[Bug Report] Imported PDF only show blank

### ISSUE THREAD

**Issue by apri1004** [ChurchApps/FreeShow#830] opened 2024-09-16 16:27 UTC
Imported PDF only show blank grey square in show window and in stage screen.

I normally import PDF from my computer, already test this at least with 2 different PDF

![image](https://github.com/user-attachments/assets/3df69d25-0f2d-45c3-b792-512545847daa)
**Version (Optional)**
 - OS: [Windows]
 - FreeShow Version: [1.2.7]

existing imported PDF, before this version is working fine.

**Comment by thebiblelover7** [comment] 2024-09-16 18:09
I can reproduce this on macOS arm64. v1.2.7

**Comment by vassbo** [comment] 2024-09-17 06:40
I can't recreate, tested 10+ PDFs. Do you think it's specific to some PDFs?
If so, could you send some not loading to dev@freeshow.app?

Also does the "Convert to images" work at all?

**Comment by gkiibzmultimedia** [comment] 2024-09-17 14:50
I have the same issue.

**Comment by apri1004** [comment] 2024-09-18 13:44
> I can't recreate, tested 10+ PDFs. Do you think it's specific to some PDFs? If so, could you send some not loading to [dev@freeshow.app](mailto:dev@freeshow.app)?
> 
> Also does the "Convert to images" work at all?

Hi vassbo,

here is the PDF files, since its not confidential..
[BAHAYA_JALAN_PINTAS[1].pdf](https://github.com/user-attachments/files/17044935/BAHAYA_JALAN_PINTAS.1.pdf)
[Bless Of Family[1].pdf](https://github.com/user-attachments/files/17044936/Bless.Of.Family.1.pdf)

**Comment by OrangeCoding2021** [comment] 2024-09-19 21:20
I can start a new issue but felt like this may fall under this same issue. On a Win 10 computer google slides generated pdf is crashing the program when trying to load it. Clock stops and buttons are highlightable but it is otherwise "frozen"

Is there any log with this program I could take a look at?

**Comment by vassbo** [comment] 2024-09-20 06:37
I think I managed to fix this, but we'll have to wait and see.

**Comment by UserDefaul** [comment] 2024-09-23 20:39
I can reproduce this using 1.2.7-beta.2 except now not only does it not import/convert to pictures, it causes the program to freeze depending on the presentation, and the only way to exit is by terminating in the task manager, causing progress to revert to the last save.

Here are the two PFD files I used in the video,
[Presentation.pdf](https://github.com/user-attachments/files/17103888/Presentation.pdf) - Does not convert to images
[Copy of 3. The Church.pdf](https://github.com/user-attachments/files/17103891/Copy.of.3.The.Church.pdf) - Causes Complete Crash

https://github.com/user-attachments/assets/9da58284-9ef8-4544-ba3c-1fc397917491

**Comment by vassbo** [comment] 2024-09-24 05:36
@UserDefaul Thanks, please wait for 1.2.8-beta.1! (Btw. 1.2.7 is newer than the pre-release 1.2.7-beta.2)

**Comment by vassbo** [comment] 2024-09-24 13:38
Try this: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.1

**Comment by UserDefaul** [comment] 2024-09-25 01:13
Hello, running the new update, I am able to import the PDFs, but they just show up as blank slides, and the convert to image function doesn't do anything. At least it doesn't crash and cause progress loss anymore though!

**Comment by vassbo** [comment] 2024-09-25 06:10
I tried both of the PDFs you sent me and both show up fine. I don't get it.

**Comment by thebiblelover7** [comment] 2024-09-25 17:01
I am still having the same issue. I will try to debug soon.

**Comment by apri1004** [comment] 2024-09-27 05:13
Hi vassbo,

really appreciate for the update, but unfortunately i'm still having this issue.
![{BC65B0F1-1FD3-471B-9A30-BE9A8A7AA2AD}](https://github.com/user-attachments/assets/ee0d45c1-475a-405c-b697-83e2a86a9871)

![{EB802EA0-3173-4CB0-8EAA-0936478DE88A}](https://github.com/user-attachments/assets/f03901f3-2309-49cc-9930-96d2302a08e2)

I'm testing it with new PDF.

**Comment by apri1004** [comment] 2024-09-30 00:18
hi vassbo,

i'm testing the new v1.2.8-beta.2, looks like it took some times and need to select another shows on the list first to load the PDF.

**Comment by vassbo** [comment] 2024-10-01 09:01
@apri1004 So you mean it works, but takes some time to load?

**Comment by apri1004** [comment] 2024-10-02 06:57
hi @vassbo,

this is what I do last time:
1. I convert the PPT file to PDF (using powerpoint)
2. I import to freeshow
3. I select the pdf, looks like this
![image](https://github.com/user-attachments/assets/00783713-ab13-4cbd-ab47-920b2e3eb344)
(it should have more than 2 slides..)
4. I select another show in the list
![image](https://github.com/user-attachments/assets/d55ad5e0-488d-4da1-9771-f6011f44ffbc)
5. then I select the imported PDF again
![image](https://github.com/user-attachments/assets/3978a898-1662-4113-9a07-582f86a8db7d)
(now it showed more than  2 slides, but still grayed box)
6. I do step no 4 couple of times, and (maybe) last time I was lucky it was showing the correct presentation

but, today this steps is not working...

I also notice that the newly imported PDF is not showing in Presentation list
![image](https://github.com/user-attachments/assets/465ab528-3694-4f62-95cc-96ca240d177c)
should be around there, right? (already do sort by names btw..)

I check with another project with different date, if the presentation not showed up in presentation list, it will also showing grey boxes only.. examples:
![image](https://github.com/user-attachments/assets/78de3c30-e530-44b4-8b96-780a9b5d02f6)
![image](https://github.com/user-attachments/assets/02a3523f-037a-4fc2-9d73-245301019432)
But, when it's on presentation list, it will show correct presentation:
![image](https://github.com/user-attachments/assets/925c1487-fba4-46ac-a34b-9dd592312b8a)
![image](https://github.com/user-attachments/assets/917766b3-72e3-48f2-aec6-e8a99b580672)

I'm not sure, if this have something to do with this bug..

Let me know if you need another check..

Thanks

**Comment by apri1004** [comment] 2024-10-02 13:37
Already tried couple of times, but looks like "convert to images" doesn't do anything..
still not showing on presentations drawer and still grayed boxes..

*I tried with new PDF

**Comment by vassbo** [comment] 2024-10-03 11:00
Thanks for your patience, please see what happens in v1.2.8: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8

**Comment by apri1004** [comment] 2024-10-03 12:59
hi @vassbo,

thank you for quick update..
I upgrade to v1.2.8 but still got grayed box..

I tried on different PC, with windows 10, still get the same behavior..

this is happened after update to new version:
![image](https://github.com/user-attachments/assets/d8ed2d95-49df-4701-bc5f-84785c3a2d09)

after selecting another show..
![image](https://github.com/user-attachments/assets/7ea3b1d1-3bda-4913-b97f-14d42af6abff)

But now it's back to greyed boxes..
Tried "convert to images" too, nothing happen..

also, i tried the new import for powerpoint/keynote, get this error..
![image](https://github.com/user-attachments/assets/c013796e-0032-4a8d-9425-8c12c256c51e)

**Comment by vassbo** [comment] 2024-10-04 12:48
All right, same PDF issue here?: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.9-beta.1

**Comment by insprittian** [comment] 2024-10-05 17:56
Hi vassbo, 
Same issue unfortunately but they loaded slowly 1 by 1 with all the previews which was promising, but after 2/3 of the slides, the output displayed grey even though the slides still had their previews. Slides that worked prior also went grey on the output. 
Is there some logging we can run to assist you with isolating and resolving the issue?

**Comment by apri1004** [comment] 2024-10-06 03:10
Hi @vassbo , 

Thank you very much..

1.2.9-beta.1 seems working fine for me when it's imported..
but, sometimes, at least for me, after couple of times switching to another show on list, it became grey again..
need to hit another show on list first before it's showing the correct presentation.

is it possible to zoom in PDF on preview?

anyway, thank you very much for this big improvement.
God bless you

**Comment by vassbo** [comment] 2024-10-07 08:38
Seems like it works randomly when it wants to work. Have not seen any pattern, but unloading and trying again often makes it work again. Maybe when it's using too much CPU.. (You can zoom with Ctrl+wheel, but that will reload the PDF.)

But when it is not working and displayed in the output it will never work for some reason (probably because it is cached), until the output is cleared, then it will work again sometimes.

This must be a bug with Chromium, and not something I think can fix. Turning off "Disable hardware acceleration" seems to help.
The alternative is to use a third party library, but that will increase the app size by a lot.

**Comment by insprittian** [comment] 2024-10-08 02:26
Will turn off the hardware acceleration in the first instance. 

Would you be open to developing a version with the third party library to see if it stabilizes the issue, or is that unrealistic / overly time consuming? 

I personally don't have any issues with a larger app size. I would assume most users aren't running the app on thin clients / low resource devices so they should be able to spare storage space, or are you referring to resource consumption (CPU, memory etc)?

**Comment by insprittian** [comment] 2024-10-08 06:22
Turning off the hardware acceleration has made it stable in my initial testing. I was doing so remotely, so might have a different experience once I power up the other displays and use them properly, but at least it didn't go grey and stop displaying in my testing. 

We will put it through a proper test on Thursday NZST and will confirm whether we have any issues, otherwise disabling the hardware acceleration seems to be a good fix / workaround.

**Comment by insprittian** [comment] 2024-10-08 08:43
Oh wait, reading over your comment @vassbo, you said to turn off the disabling of the hardware acceleration, which is enabling it? I had it enabled previously and have disabled it and the PDF import & output is working well from my remote tests... That is the opposite of what you expected / suggested?

**Comment by vassbo** [comment] 2024-10-08 08:48
True! I guess it depends, but if it works it does not matter.

**Closed** 2024-10-09 07:59 UTC
Labels: bug
